spring.application.name=tsetmc-api
# Server
server.port=9000
server.servlet.context-path=/tsetmc
# External APIs
external.tsetmc.base-url=https://cdn.tsetmc.com/api
# API Documentation
springdoc.swagger-ui.path=/doc.html
# Logging
logging.level.com.ernoxin=DEBUG