server.port=9000
server.servlet.context-path=/tsetmc
spring.application.name=tsetmc-api
external.tsetmc.base-url=https://cdn.tsetmc.com/api
springdoc.swagger-ui.path=/doc.html
logging.level.com.ernoxin=DEBUG